services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  flower:
      image: mher/flower:latest
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5555:5555"
      depends_on:
        - redis
