services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  flower:
      image: mher/flower:latest
      command: ['flower', '--broker=redis://redis:6379', '--port=5555']
      ports:
        - "5555:5555"
      depends_on:
        - redis
